### ISSUE TITLE
CustomColumnFormatter is receiving the value already converted to a String

### ISSUE THREAD

**Issue by bcmedeiros** [bonprix/vaadin-excel-exporter#1]
The invocations of the method `org.vaadin.addons.ExportToExcelUtility.applyColumnFormatter(Object[], ExportExcelComponentConfiguration, Object, int, Object)` should be:

```
applyColumnFormatter(visibleColumns, componentConfiguration, itemId, columns, obj)
```

instead of:

```
applyColumnFormatter(visibleColumns, componentConfiguration, itemId, columns, obj.toString()) 
```

As a workaround, we can get the whole object and re-get the proper value, but it should be fixed.

**Comment by KartikSuba** [comment]
Done necessary changes with version 1.0.4.
Thanks for the feedback :)

Best Regards,
Kartik
