### ISSUE TITLE
ExportToExcelUtility.getAllMethods is not working correctly

### ISSUE THREAD

**Issue by karakal** [bonprix/vaadin-excel-exporter#17]
The method getAllMethods(....) in the Class ExportToExcelUtility is not correct:

```
Method method;
try {
  method = type.getMethod("get" + name);
  if (method == null) {
    method = type.getMethod("is" + name);
  }
  if (method != null) {
    map.put(field.getName(), method);
  }
}
catch (NoSuchMethodException | SecurityException e) {
  e.printStackTrace();
}
```
if you are using a boolean in your Class it will throw a java.lang.NoSuchMethodException and print a stacktrace instead of searching for the Method "is"+name.

I created a pull request. Error handling has to be implemented better (marked it with a TODO)

**Comment by KartikSuba** [comment]
Resolved in version 1.0.6
