### ISSUE TITLE
handling the nestedBeanProperties when the container is a BeanItemContainer

### ISSUE THREAD

**Issue by npocze-intrend** [bonprix/vaadin-excel-exporter#3]
To handle the nestedBeanProperties when using a BeanItemContainer as containerDataSource I would suggest the following modification:

org.vaadin.addons.ExportToExcelUtility
method: 
addGenericDataRow(Object[], XSSFWorkbook, ExportExcelSheetConfiguration, ExportExcelComponentConfiguration, Object, Integer, Boolean)

...
else if (componentConfiguration.getGrid() != null && (componentConfiguration.getGrid()
                                                                                           .getContainerDataSource() instanceof IndexedContainer ||
                                                                                           componentConfiguration.getGrid()
                                                                                           .getContainerDataSource() instanceof BeanItemContainer ))

**Comment by KartikSuba** [comment]
Resolved in version 1.0.6
