### ISSUE TITLE
Missing JavaDoc

### ISSUE THREAD

**Issue by kamuffe** [bonprix/vaadin-excel-exporter#6]
Please add JavaDoc to your code.

e.g. Currencies are added as strings with my configuration and I have no clue why it is so.
JavaDoc helps to find the issue and is in general good practice ;)

Best Regards.

**Comment by KartikSuba** [comment]
JavaDoc has been added with the release of version 1.0.4. Thanks for the suggestion :)

Best Regards,
Kartik
