### ISSUE TITLE
Please use collection interfaces instead of direct classes

### ISSUE THREAD

**Issue by futaz** [bonprix/vaadin-excel-exporter#7]
Please, use interfaces from Java Collections API (eg. Collection, List, Set or Map) instead of direct classes (e.g. ArrayList or HashMap) as arguments in the project. It makes very uncomfortable to configure the exporter, because most of the time I have only one config and now I have to instantiate a new ArrayList or HashMap, adding/putting that single config to it and setting that ArrayList/HashMap instance to the export.

If you switch to interfaces, the following will be possible:
`
new ExportExcelComponentConfigurationBuilder().withColumnFormatters(Collections.singletonMap(myCustomFormatter)).build();
`
or
`
new ExportExcelSheetConfigurationBuilder().withComponentConfigs(Arrays.asList(myComponentConfig)).build();
`

Thanks,
 futaz

**Comment by KartikSuba** [comment]
Replaced all the usages of classes with interfaces. Thanks for the suggestion :)

Best Regards,
Kartik

**Comment by bcmedeiros** [comment]
Thank you very much, I had it locally and was about to create a PR ;)
